services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_reservation_system
    volumes:
      - .:/code
      - /code/.venv
    depends_on:
      - postgres_db
    
    ports:
      - "8000:8000"

  postgres_db:
    image: postgres:16
    restart: always
    container_name: PostgresContt
    environment:
      - POSTGRES_USER=<username>
      - POSTGRES_PASSWORD=<password>
      - POSTGRES_DB=<dbname>
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data



volumes:
  postgres_db:
    driver: local

networks:
  default:
    driver: bridge
